import AnimatedText from "@amigos/components/AnimatedText";
import Layout from "@amigos/components/Layout";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
		<>
			<Head>
			<title>Zupancic Hnos. | Inicio</title>
        <meta name="description" content="Generated by create next app" />
			</Head>
			<main className="flex flex-col min-h-screen pt-[60px] bg-home bg-cover bg-center text-light">
				<Layout>
					<div className="w-full pl-6 flex flex-col gap-10">
						<AnimatedText text="Asesoramiento contable impositivo" className="w-full mt-24 font-bold text-4xl" />
						<p className="flex flex-col w-full">
							<span className="text-4xl font-bold">
								<span className="text-primary">Z</span>UPANCIC
							</span>
							<span className="text-4xl font-bold">
								<span className="text-primary">H</span>ERMANOS
							</span>
						</p>
						<Link href={"/about"} className="px-6 py-2 bg-primary/90 w-fit">
							Más información
						</Link>
					</div>
				</Layout>
			</main>
		</>
  )
}
